### ISSUE TITLE
Example 16 has wrong colors on OS X

### ISSUE THREAD

**Issue by buzmeg** [unknownue/vulkan-tutorial-rust#9]
Example 16 looks like this on my machine, while the snapshot has the standard RGB in the different corners.

![Screen Shot 2019-06-15 at 12 51 00 AM](https://user-images.githubusercontent.com/4359833/59548694-f0435b80-8f07-11e9-8cbc-207ff3b27683.png)

**Comment by unknownue** [comment]
This problem does not reproduce on my machine. Example 15 is the first triangle appears on screen. 
Does Example 15 share the same problem?

**Comment by buzmeg** [comment]
Yes, 15 and 16 look the same.

**Comment by unknownue** [comment]
I suggest you try running the example code of [ash](https://github.com/MaikKlein/ash). This help me to figure out if it's the problem of my code, a machine specific problem, or any bug issure in SDK.
I can't debug a problem which does not reproduce on my machine.

**Comment by unknownue** [comment]
Since there is no response for a long time. I would close this issue. If this problem still reproduces, open the issue again.

**Comment by buzmeg** [comment]
Can confirm that this still exists as of vulkansdk-macos-1.1.114.0.  Running both triangle and texture examples in ash work fine.

Edit: Can't reopen bug that has been closed by collaborators (gee, thanks, github).  If this doesn't reopen in a couple days, I will file another bug.

**Comment by buzmeg** [comment]
Can confirm that this fails on OS X 10.12.6 and succeeds on 10.14.5.

**Comment by unknownue** [comment]
I have no access to machine running on previous version of macOS.
Since metal is updated along with macOS, the problem may cause by some missing feature of metal or compatibility issue with MoltanVK.

To farther identify the problem, you may try to run the original C++ version of example 16 on 10.12.6.
If this problem still exists, it means OSX 10.12 is not compatible with Vulkan.
If this problem disappears, something is wrong when bridging Rust and Vulkan.
If you find fixing this issue is meaningless, just close this issue.

**Comment by buzmeg** [comment]
Yeah, let's close this as a "Won't Fix".  It's probably a real issue, but it's probably not worth running down if nobody has computers for which it matters anymore.
